slurm launcher - improve the discovery of cosmos_rl path (#573)
# The problem

Here is the issue I encountered on two of the clusters, where `import
cosmos_rl` emits lines of warnings.
And these extra lines caused `cd $(python -c "import
cosmos_rl,os;print(os.path.dirname(os.path.dirname(cosmos_rl.__file__)))")`
to fail.

vincentz@xxx-001:/$ python

```Python

Python 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import cosmos_rl
INFO 02-10 14:27:43 [__init__.py:241] Automatically detected platform cuda.
[cosmos] 2026-02-10 14:27:44,122 - cosmos - ERROR - Failed to import VLLM Rollout. Please make sure vllm is installed. Error: cannot import name 'ResponsePrompt' from 'openai.types.responses' (/usr/local/lib/python3.12/dist-packages/openai/types/responses/__init__.py)
/usr/local/lib/python3.12/dist-packages
```

# The solution

The fix is basically to surpress the extra logs via
`disable(logging.CRITICAL`